-- 1. 은행/금융기관 코드(BANK_CODE)
INSERT INTO common_codes (category, code, description) VALUES
('BANK_CODE', '000', '알수없음'),
('BANK_CODE', '001', '한국은행'),
('BANK_CODE', '002', '산업은행'),
('BANK_CODE', '003', '기업은행'),
('BANK_CODE', '004', '국민은행'),
('BANK_CODE', '005', '외환은행'),
('BANK_CODE', '007', '수협중앙회'),
('BANK_CODE', '008', '수출입은행'),
('BANK_CODE', '011', '농협은행'),
('BANK_CODE', '012', '지역농.축협'),
('BANK_CODE', '020', '우리은행'),
('BANK_CODE', '023', 'SC은행'),
('BANK_CODE', '027', '한국씨티은행'),
('BANK_CODE', '031', '대구은행'),
('BANK_CODE', '032', '부산은행'),
('BANK_CODE', '034', '광주은행'),
('BANK_CODE', '035', '제주은행'),
('BANK_CODE', '037', '전북은행'),
('BANK_CODE', '039', '경남은행'),
('BANK_CODE', '045', '새마을금고중앙회'),
('BANK_CODE', '048', '신협중앙회'),
('BANK_CODE', '050', '상호저축은행'),
('BANK_CODE', '051', '중국은행'),
('BANK_CODE', '052', '모건스탠리은행'),
('BANK_CODE', '054', 'HSBC은행'),
('BANK_CODE', '055', '도이치은행'),
('BANK_CODE', '056', '알비에스피엘씨은행'),
('BANK_CODE', '057', '제이피모간체이스은행'),
('BANK_CODE', '058', '미즈호은행'),
('BANK_CODE', '059', '미쓰비시도쿄UFJ은행'),
('BANK_CODE', '060', 'BOA은행'),
('BANK_CODE', '061', '비엔피파리바은행'),
('BANK_CODE', '062', '중국공상은행'),
('BANK_CODE', '063', '중국은행'),
('BANK_CODE', '064', '산림조합중앙회'),
('BANK_CODE', '065', '대화은행'),
('BANK_CODE', '066', '교통은행'),
('BANK_CODE', '071', '우체국'),
('BANK_CODE', '076', '신용보증기금'),
('BANK_CODE', '077', '기술보증기금'),
('BANK_CODE', '081', 'KEB하나은행'),
('BANK_CODE', '088', '신한은행'),
('BANK_CODE', '089', '케이뱅크'),
('BANK_CODE', '090', '카카오뱅크'),
('BANK_CODE', '092', '토스뱅크'),
('BANK_CODE', '093', '한국주택금융공사'),
('BANK_CODE', '094', '서울보증보험'),
('BANK_CODE', '095', '경찰청'),
('BANK_CODE', '096', '한국전자금융(주)'),
('BANK_CODE', '099', '금융결제원'),
('BANK_CODE', '102', '대신저축은행'),
('BANK_CODE', '103', '에스비아이저축은행'),
('BANK_CODE', '104', '에이치케이저축은행'),
('BANK_CODE', '105', '웰컴저축은행'),
('BANK_CODE', '106', '신한저축은행'),
('BANK_CODE', '209', '유안타증권'),
('BANK_CODE', '218', '현대증권'),
('BANK_CODE', '221', '골든브릿지투자증권'),
('BANK_CODE', '222', '한양증권'),
('BANK_CODE', '223', '리딩투자증권'),
('BANK_CODE', '224', 'BNK투자증권'),
('BANK_CODE', '225', 'IBK투자증권'),
('BANK_CODE', '226', 'KB투자증권'),
('BANK_CODE', '227', 'KTB투자증권'),
('BANK_CODE', '230', '미래에셋증권'),
('BANK_CODE', '238', '대우증권'),
('BANK_CODE', '240', '삼성증권'),
('BANK_CODE', '243', '한국투자증권'),
('BANK_CODE', '261', '교보증권'),
('BANK_CODE', '262', '하이투자증권'),
('BANK_CODE', '263', 'HMC투자증권'),
('BANK_CODE', '264', '키움증권'),
('BANK_CODE', '265', '이베스트투자증권'),
('BANK_CODE', '266', 'SK증권'),
('BANK_CODE', '267', '대신증권'),
('BANK_CODE', '269', '한화투자증권'),
('BANK_CODE', '270', '하나대투증권'),
('BANK_CODE', '278', '신한금융투자'),
('BANK_CODE', '279', 'DB금융투자'),
('BANK_CODE', '280', '유진투자증권'),
('BANK_CODE', '287', '메리츠종합금융증권'),
('BANK_CODE', '289', 'NH투자증권'),
('BANK_CODE', '290', '부국증권'),
('BANK_CODE', '291', '신영증권'),
('BANK_CODE', '292', '엘아이지투자증권'),
('BANK_CODE', '293', '한국증권금융'),
('BANK_CODE', '294', '펀드온라인코리아'),
('BANK_CODE', '295', '우리종합금융'),
('BANK_CODE', '296', '삼성선물'),
('BANK_CODE', '297', '외환선물'),
('BANK_CODE', '298', '현대선물');

-- 2. 계좌 종류 (ACCOUNT_TYPE)
INSERT INTO common_codes (category, code, description) VALUES
('ACCOUNT_TYPE', 'CHECKING', '입출금'),
('ACCOUNT_TYPE', 'SAVING', '적금'),
('ACCOUNT_TYPE', 'LOAN', '대출'),
('ACCOUNT_TYPE', 'PENSION', '연금'),
('ACCOUNT_TYPE', 'TRUST', '신탁'),
('ACCOUNT_TYPE', 'FOREIGN_CURRENCY', '외화'),
('ACCOUNT_TYPE', 'IRP', '퇴직연금'),
('ACCOUNT_TYPE', 'STOCK', '주식');

-- 3. 거래 타입 (TRANSACTION_TYPE)
INSERT INTO common_codes (category, code, description) VALUES
('TRANSACTION_TYPE', 'DEPOSIT', '입금'),
('TRANSACTION_TYPE', 'WITHDRAW', '출금');

-- 4. 거래 방식 (TRANSACTION_METHOD)
INSERT INTO common_codes (category, code, description) VALUES
('TRANSACTION_METHOD', 'ATM', 'ATM 거래'),
('TRANSACTION_METHOD', 'TRANSFER', '계좌이체'),
('TRANSACTION_METHOD', 'BANK_TRANSFER', '은행이체'),
('TRANSACTION_METHOD', 'AUTOMATIC_TRANSFER', '자동이체'),
('TRANSACTION_METHOD', 'CARD', '카드결제'),
('TRANSACTION_METHOD', 'INTEREST', '이자'),
('TRANSACTION_METHOD', 'ETC', '기타');

-- 5. 분석 기간 타입 (ANALYSIS_TYPES)
INSERT INTO common_codes (category, code, description) VALUES
('ANALYSIS_TYPE', 'DAILY', '일간'),
('ANALYSIS_TYPE', 'WEEKLY', '주간'),
('ANALYSIS_TYPE', 'MONTHLY', '월간'),
('ANALYSIS_TYPE', 'YEARLY', '연간');

-- 6. 분석 대상 (ANALYSIS_ABOUT)
INSERT INTO common_codes (category, code, description) VALUES
('ANALYSIS_ABOUT', 'TOTAL_SPENDING', '총 지출'),
('ANALYSIS_ABOUT', 'TOTAL_INCOME', '총 수입');