# Generated by Django 5.2.8 on 2025-12-02 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="계좌번호"
                    ),
                ),
                ("bank_code", models.CharField(max_length=10, verbose_name="은행코드")),
                (
                    "account_type",
                    models.CharField(max_length=10, verbose_name="계좌종류"),
                ),
                ("name", models.CharField(max_length=60, verbose_name="계좌별칭")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "계좌",
                "db_table": "accounts",
            },
        ),
    ]
