services:
  db:
    image: postgres:16-alpine
    container_name: dev_budget_db
    environment:
      # POSTGRES_* 변수는 컨테이너 초기화에 사용됩니다.
      POSTGRES_DB: budget
      POSTGRES_USER: budget_admin
      POSTGRES_PASSWORD: budget1234
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init_data:/docker-entrypoint-initdb.d
    ports:
      - "5440:5432" # 로컬 5440 포트 -> 컨테이너 5432 포트
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U budget_admin -d budget" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7.0-alpine
    container_name: dev_budgeting_redis
    expose:
      - 6379

  web:
    build:
      context: ..                   # 빌드 컨텍스트를 프로젝트 루트(상위)로 지정
      dockerfile: docker/Dockerfile # 컨텍스트 내에서 Dockerfile의 경로를 명시
    container_name: dev_budgeting_site
    # run.sh 스크립트를 실행하도록 command를 변경
    command: sh -c "python manage.py migrate --noinput && sh /usr/src/app/scripts/run.sh"
    volumes:
      - ../:/usr/src/app                     # 프로젝트 루트(secrets.json 포함)를 /app에 마운트
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev
      # secrets.json에서 로드하도록 권장되지만, 개발 편의상 명시된 변수 유지
      - SECRET_KEY=c924tofl&x+y@d73!(3svrhf5o9+@f@z4i=0wok8^1cg4vpz=b
      - DB_USERNAME=budget_admin
      - DB_PASSWORD=budget1234
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=budget
      - DB_URL=postgres://budget_admin:budget1234@db:5432/budget
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_MINUTES=1440
    depends_on:
      db:
        condition: service_healthy # DB 상태 점검(healthcheck)이 성공할 때까지 기다립니다.

  celery_worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: dev_budgeting_worker
    command: sh -c "celery -A core worker -l info"
    volumes:
      - ../:/usr/src/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev
    depends_on:
      - db
      - redis
      - web

  celery_beat:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: dev_budgeting_beat
    command: sh -c "celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - ../:/usr/src/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev
    depends_on:
      - db
      - redis
      - web

volumes:
  db-data: